artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://zenodo.org/record/1188976/files/Audio_Speech_Actors_01-24.zip?download=1
  local_data_file: artifacts/data_ingestion/ravdess.zip
  unzip_dir: artifacts/data_ingestion
